version: '3'
services:
  mysql:
    image: mysql:8
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: happy-chat
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s  # 健康检查的间隔，这里设置为30秒
      timeout: 3s
      retries: 5
  
  logic:
    image: woshiaotian/chat-logic:v0.1.2
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config.logic.yaml:/data/config.logic.yaml
  
  broker:
    image: woshiaotian/chat-broker:v0.1.2
    depends_on:
      - logic
    volumes:
      - ./config.broker.yaml:/data/config.broker.yaml
#    ports:
#      - 18224:18224
  
  chat-ui:
    image: woshiaotian/chat-ui:v0.0.3
    depends_on:
      - broker
    ports:
      - 80:80
    environment:
      API_HOST: broker:18224
