logic_dealer:
  # 自定义了resolver
  # dig @8.8.8.8 _grpclb._tcp.logic.vearne.cc srv
  # 在dns中 _grpclb._tcp.logic.vearne.cc -> 0 50 28223 logic1.vearne.cc
  #        _grpclb._tcp.logic.vearne.cc -> 0 50 28224 logic2.vearne.cc
  # address: "127.0.0.1:18223"
  address: "srv://8.8.8.8/logic.vearne.cc"
  
logger:
  # 1. "info"
  # 2. "debug"
  # 3. "error"
  level: "debug"
  filepath: "/var/log/chat_broker.log"
#  listen_address: ":19093"

# broker的配置
broker:
  ws_address: ":18224"
  grpc_address: ":18225"

# 用Ping检查Client是否退出或者掉线
# 超过maxWait就认为Client已经掉线
ping:
  interval: "3s"
  maxWait: "20s"
