// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broker.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignalTypeEnum int32

const (
	SignalTypeEnum_PartnerExit   SignalTypeEnum = 0
	SignalTypeEnum_CreateSession SignalTypeEnum = 1
	SignalTypeEnum_DeleteMsg     SignalTypeEnum = 2
)

var SignalTypeEnum_name = map[int32]string{
	0: "PartnerExit",
	1: "CreateSession",
	2: "DeleteMsg",
}

var SignalTypeEnum_value = map[string]int32{
	"PartnerExit":   0,
	"CreateSession": 1,
	"DeleteMsg":     2,
}

func (x SignalTypeEnum) String() string {
	return proto.EnumName(SignalTypeEnum_name, int32(x))
}

func (SignalTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{0}
}

type PushRequest struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{0}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type PushResp struct {
	Code                 CodeEnum `protobuf:"varint,1,opt,name=code,proto3,enum=proto.CodeEnum" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResp) Reset()         { *m = PushResp{} }
func (m *PushResp) String() string { return proto.CompactTextString(m) }
func (*PushResp) ProtoMessage()    {}
func (*PushResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{1}
}

func (m *PushResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResp.Unmarshal(m, b)
}
func (m *PushResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResp.Marshal(b, m, deterministic)
}
func (m *PushResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResp.Merge(m, src)
}
func (m *PushResp) XXX_Size() int {
	return xxx_messageInfo_PushResp.Size(m)
}
func (m *PushResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushResp proto.InternalMessageInfo

func (m *PushResp) GetCode() CodeEnum {
	if m != nil {
		return m.Code
	}
	return CodeEnum_C000
}

func (m *PushResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PushDialogue struct {
	SenderId             uint64   `protobuf:"varint,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	SessionId            uint64   `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ReceiverId           uint64   `protobuf:"varint,3,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushDialogue) Reset()         { *m = PushDialogue{} }
func (m *PushDialogue) String() string { return proto.CompactTextString(m) }
func (*PushDialogue) ProtoMessage()    {}
func (*PushDialogue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{2}
}

func (m *PushDialogue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushDialogue.Unmarshal(m, b)
}
func (m *PushDialogue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushDialogue.Marshal(b, m, deterministic)
}
func (m *PushDialogue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushDialogue.Merge(m, src)
}
func (m *PushDialogue) XXX_Size() int {
	return xxx_messageInfo_PushDialogue.Size(m)
}
func (m *PushDialogue) XXX_DiscardUnknown() {
	xxx_messageInfo_PushDialogue.DiscardUnknown(m)
}

var xxx_messageInfo_PushDialogue proto.InternalMessageInfo

func (m *PushDialogue) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *PushDialogue) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PushDialogue) GetReceiverId() uint64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *PushDialogue) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PushSignal struct {
	SignalType SignalTypeEnum `protobuf:"varint,1,opt,name=signalType,proto3,enum=proto.SignalTypeEnum" json:"signalType,omitempty"`
	SenderId   uint64         `protobuf:"varint,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId uint64         `protobuf:"varint,3,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	SessionId  uint64         `protobuf:"varint,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*PushSignal_Partner
	//	*PushSignal_MsgId
	Data                 isPushSignal_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PushSignal) Reset()         { *m = PushSignal{} }
func (m *PushSignal) String() string { return proto.CompactTextString(m) }
func (*PushSignal) ProtoMessage()    {}
func (*PushSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{3}
}

func (m *PushSignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushSignal.Unmarshal(m, b)
}
func (m *PushSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushSignal.Marshal(b, m, deterministic)
}
func (m *PushSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSignal.Merge(m, src)
}
func (m *PushSignal) XXX_Size() int {
	return xxx_messageInfo_PushSignal.Size(m)
}
func (m *PushSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSignal.DiscardUnknown(m)
}

var xxx_messageInfo_PushSignal proto.InternalMessageInfo

func (m *PushSignal) GetSignalType() SignalTypeEnum {
	if m != nil {
		return m.SignalType
	}
	return SignalTypeEnum_PartnerExit
}

func (m *PushSignal) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *PushSignal) GetReceiverId() uint64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *PushSignal) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type isPushSignal_Data interface {
	isPushSignal_Data()
}

type PushSignal_Partner struct {
	Partner *AccountInfo `protobuf:"bytes,5,opt,name=partner,proto3,oneof"`
}

type PushSignal_MsgId struct {
	MsgId uint64 `protobuf:"varint,6,opt,name=msgId,proto3,oneof"`
}

func (*PushSignal_Partner) isPushSignal_Data() {}

func (*PushSignal_MsgId) isPushSignal_Data() {}

func (m *PushSignal) GetData() isPushSignal_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PushSignal) GetPartner() *AccountInfo {
	if x, ok := m.GetData().(*PushSignal_Partner); ok {
		return x.Partner
	}
	return nil
}

func (m *PushSignal) GetMsgId() uint64 {
	if x, ok := m.GetData().(*PushSignal_MsgId); ok {
		return x.MsgId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PushSignal) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PushSignal_Partner)(nil),
		(*PushSignal_MsgId)(nil),
	}
}

type AccountInfo struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{4}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.SignalTypeEnum", SignalTypeEnum_name, SignalTypeEnum_value)
	proto.RegisterType((*PushRequest)(nil), "proto.PushRequest")
	proto.RegisterType((*PushResp)(nil), "proto.PushResp")
	proto.RegisterType((*PushDialogue)(nil), "proto.PushDialogue")
	proto.RegisterType((*PushSignal)(nil), "proto.PushSignal")
	proto.RegisterType((*AccountInfo)(nil), "proto.AccountInfo")
}

func init() { proto.RegisterFile("broker.proto", fileDescriptor_f209535e190f2bed) }

var fileDescriptor_f209535e190f2bed = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x6d, 0xba, 0x69, 0x76, 0x3b, 0xd9, 0xdd, 0x66, 0x8d, 0x40, 0x51, 0x85, 0x50, 0x15, 0x2e,
	0x15, 0x48, 0x3d, 0x14, 0xc1, 0x81, 0xdb, 0x6e, 0x77, 0xc5, 0xf6, 0x50, 0x54, 0xb9, 0xfc, 0x80,
	0x9b, 0x0c, 0x21, 0x6a, 0x62, 0x07, 0xdb, 0x41, 0x20, 0x71, 0xe2, 0x7f, 0xf9, 0x07, 0x14, 0x3b,
	0x4d, 0xd3, 0x22, 0xc1, 0x29, 0x7e, 0xcf, 0x6f, 0x26, 0xef, 0x79, 0x06, 0x2e, 0xb7, 0x52, 0xec,
	0x50, 0xce, 0x4a, 0x29, 0xb4, 0x20, 0x03, 0xf3, 0x19, 0xfb, 0xb9, 0x48, 0xb3, 0xd8, 0x72, 0xd1,
	0x6b, 0xf0, 0xd7, 0x95, 0xfa, 0x42, 0xf1, 0x6b, 0x85, 0x4a, 0x93, 0xe7, 0x30, 0x64, 0x71, 0x2c,
	0x2a, 0xae, 0x97, 0x49, 0xe8, 0x4c, 0x9c, 0xa9, 0x4b, 0x0f, 0x44, 0x74, 0x0b, 0x17, 0x56, 0xac,
	0x4a, 0xf2, 0x12, 0xdc, 0x58, 0x24, 0x68, 0x44, 0xd7, 0xf3, 0x91, 0x6d, 0x37, 0x5b, 0x88, 0x04,
	0x1f, 0x78, 0x55, 0x50, 0x73, 0x49, 0x02, 0x38, 0x2b, 0x54, 0x1a, 0xf6, 0x27, 0xce, 0x74, 0x48,
	0xeb, 0x63, 0xf4, 0xcb, 0x81, 0xcb, 0xba, 0xc7, 0x7d, 0xc6, 0x72, 0x91, 0x56, 0x48, 0xc6, 0x70,
	0xa1, 0x90, 0x27, 0x28, 0xdb, 0x1f, 0xb6, 0xb8, 0x76, 0xa3, 0x50, 0xa9, 0x4c, 0xf0, 0x65, 0x62,
	0x9a, 0xb8, 0xf4, 0x40, 0x90, 0x17, 0x00, 0x12, 0x63, 0xcc, 0xbe, 0x99, 0xda, 0x33, 0x73, 0xdd,
	0x61, 0x48, 0x08, 0xe7, 0xb1, 0xe0, 0x1a, 0xb9, 0x0e, 0x5d, 0x63, 0x60, 0x0f, 0xa3, 0xdf, 0x0e,
	0x40, 0x6d, 0x62, 0x93, 0xa5, 0x9c, 0xe5, 0xe4, 0x2d, 0x80, 0x32, 0xa7, 0x4f, 0x3f, 0xca, 0x7d,
	0xa0, 0xa7, 0x4d, 0xa0, 0x4d, 0x7b, 0x61, 0x62, 0x75, 0x84, 0x47, 0xce, 0xfb, 0x27, 0xce, 0xff,
	0xe7, 0xed, 0x28, 0x99, 0x7b, 0x9a, 0x6c, 0x06, 0xe7, 0x25, 0x93, 0x9a, 0xa3, 0x0c, 0x07, 0x13,
	0x67, 0xea, 0xcf, 0x49, 0xe3, 0xe6, 0xb6, 0x19, 0x05, 0xff, 0x2c, 0x1e, 0x7b, 0x74, 0x2f, 0x22,
	0xcf, 0x60, 0x50, 0xa8, 0x74, 0x99, 0x84, 0x5e, 0xdd, 0xe9, 0xb1, 0x47, 0x2d, 0xbc, 0xf3, 0xc0,
	0x4d, 0x98, 0x66, 0xd1, 0x07, 0xf0, 0x3b, 0x95, 0xff, 0x1e, 0x72, 0x1d, 0x8b, 0x67, 0xf1, 0xee,
	0x23, 0x2b, 0xb0, 0x19, 0x5c, 0x8b, 0x5f, 0x2d, 0xe0, 0xfa, 0xf8, 0x41, 0xc8, 0x08, 0xfc, 0xb5,
	0x75, 0xf1, 0xf0, 0x3d, 0xd3, 0x41, 0x8f, 0xdc, 0xc0, 0xd5, 0x42, 0x22, 0xd3, 0xb8, 0xb1, 0x71,
	0x02, 0x87, 0x5c, 0xc1, 0xf0, 0x1e, 0x73, 0xd4, 0xb8, 0x52, 0x69, 0xd0, 0x9f, 0xff, 0x04, 0xef,
	0xce, 0xac, 0x25, 0x79, 0x0f, 0x84, 0xda, 0x37, 0x59, 0xa9, 0xb4, 0xdd, 0x88, 0x27, 0x4d, 0xd8,
	0xee, 0x9a, 0x8c, 0x47, 0x1d, 0xd2, 0xec, 0xdf, 0x3b, 0x08, 0x0e, 0xb5, 0xcd, 0x20, 0x6f, 0x3a,
	0x22, 0x4b, 0xfd, 0x55, 0xb7, 0xf5, 0x0c, 0x7e, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x03,
	0x28, 0x91, 0x1b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerClient interface {
	// 接收logic推送过来的数据
	ReceiveMsgDialogue(ctx context.Context, in *PushDialogue, opts ...grpc.CallOption) (*PushResp, error)
	ReceiveMsgSignal(ctx context.Context, in *PushSignal, opts ...grpc.CallOption) (*PushResp, error)
}

type brokerClient struct {
	cc *grpc.ClientConn
}

func NewBrokerClient(cc *grpc.ClientConn) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) ReceiveMsgDialogue(ctx context.Context, in *PushDialogue, opts ...grpc.CallOption) (*PushResp, error) {
	out := new(PushResp)
	err := c.cc.Invoke(ctx, "/proto.Broker/ReceiveMsgDialogue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ReceiveMsgSignal(ctx context.Context, in *PushSignal, opts ...grpc.CallOption) (*PushResp, error) {
	out := new(PushResp)
	err := c.cc.Invoke(ctx, "/proto.Broker/ReceiveMsgSignal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
type BrokerServer interface {
	// 接收logic推送过来的数据
	ReceiveMsgDialogue(context.Context, *PushDialogue) (*PushResp, error)
	ReceiveMsgSignal(context.Context, *PushSignal) (*PushResp, error)
}

// UnimplementedBrokerServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (*UnimplementedBrokerServer) ReceiveMsgDialogue(ctx context.Context, req *PushDialogue) (*PushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMsgDialogue not implemented")
}
func (*UnimplementedBrokerServer) ReceiveMsgSignal(ctx context.Context, req *PushSignal) (*PushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMsgSignal not implemented")
}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

func _Broker_ReceiveMsgDialogue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDialogue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ReceiveMsgDialogue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/ReceiveMsgDialogue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ReceiveMsgDialogue(ctx, req.(*PushDialogue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ReceiveMsgSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ReceiveMsgSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/ReceiveMsgSignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ReceiveMsgSignal(ctx, req.(*PushSignal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMsgDialogue",
			Handler:    _Broker_ReceiveMsgDialogue_Handler,
		},
		{
			MethodName: "ReceiveMsgSignal",
			Handler:    _Broker_ReceiveMsgSignal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker.proto",
}
