// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: broker.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignalTypeEnum int32

const (
	SignalTypeEnum_PartnerExit   SignalTypeEnum = 0
	SignalTypeEnum_CreateSession SignalTypeEnum = 1
	SignalTypeEnum_DeleteMsg     SignalTypeEnum = 2
)

var SignalTypeEnum_name = map[int32]string{
	0: "PartnerExit",
	1: "CreateSession",
	2: "DeleteMsg",
}

var SignalTypeEnum_value = map[string]int32{
	"PartnerExit":   0,
	"CreateSession": 1,
	"DeleteMsg":     2,
}

func (x SignalTypeEnum) String() string {
	return proto.EnumName(SignalTypeEnum_name, int32(x))
}

func (SignalTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{0}
}

type PushRequest struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{0}
}
func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return m.Size()
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type PushResp struct {
	Code                 CodeEnum `protobuf:"varint,1,opt,name=code,proto3,enum=proto.CodeEnum" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResp) Reset()         { *m = PushResp{} }
func (m *PushResp) String() string { return proto.CompactTextString(m) }
func (*PushResp) ProtoMessage()    {}
func (*PushResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{1}
}
func (m *PushResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResp.Merge(m, src)
}
func (m *PushResp) XXX_Size() int {
	return m.Size()
}
func (m *PushResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushResp proto.InternalMessageInfo

func (m *PushResp) GetCode() CodeEnum {
	if m != nil {
		return m.Code
	}
	return CodeEnum_C000
}

func (m *PushResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PushDialogue struct {
	SenderId             uint64   `protobuf:"varint,1,opt,name=senderId,proto3" json:"senderId,omitempty"`
	SessionId            uint64   `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ReceiverId           uint64   `protobuf:"varint,3,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushDialogue) Reset()         { *m = PushDialogue{} }
func (m *PushDialogue) String() string { return proto.CompactTextString(m) }
func (*PushDialogue) ProtoMessage()    {}
func (*PushDialogue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{2}
}
func (m *PushDialogue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushDialogue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushDialogue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushDialogue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushDialogue.Merge(m, src)
}
func (m *PushDialogue) XXX_Size() int {
	return m.Size()
}
func (m *PushDialogue) XXX_DiscardUnknown() {
	xxx_messageInfo_PushDialogue.DiscardUnknown(m)
}

var xxx_messageInfo_PushDialogue proto.InternalMessageInfo

func (m *PushDialogue) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *PushDialogue) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PushDialogue) GetReceiverId() uint64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *PushDialogue) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PushSignal struct {
	SignalType SignalTypeEnum `protobuf:"varint,1,opt,name=signalType,proto3,enum=proto.SignalTypeEnum" json:"signalType,omitempty"`
	SenderId   uint64         `protobuf:"varint,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	ReceiverId uint64         `protobuf:"varint,3,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	SessionId  uint64         `protobuf:"varint,4,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*PushSignal_Partner
	//	*PushSignal_MsgId
	Data                 isPushSignal_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PushSignal) Reset()         { *m = PushSignal{} }
func (m *PushSignal) String() string { return proto.CompactTextString(m) }
func (*PushSignal) ProtoMessage()    {}
func (*PushSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{3}
}
func (m *PushSignal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushSignal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSignal.Merge(m, src)
}
func (m *PushSignal) XXX_Size() int {
	return m.Size()
}
func (m *PushSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSignal.DiscardUnknown(m)
}

var xxx_messageInfo_PushSignal proto.InternalMessageInfo

type isPushSignal_Data interface {
	isPushSignal_Data()
	MarshalTo([]byte) (int, error)
	Size() int
}

type PushSignal_Partner struct {
	Partner *AccountInfo `protobuf:"bytes,5,opt,name=partner,proto3,oneof" json:"partner,omitempty"`
}
type PushSignal_MsgId struct {
	MsgId string `protobuf:"bytes,6,opt,name=msgId,proto3,oneof" json:"msgId,omitempty"`
}

func (*PushSignal_Partner) isPushSignal_Data() {}
func (*PushSignal_MsgId) isPushSignal_Data()   {}

func (m *PushSignal) GetData() isPushSignal_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PushSignal) GetSignalType() SignalTypeEnum {
	if m != nil {
		return m.SignalType
	}
	return SignalTypeEnum_PartnerExit
}

func (m *PushSignal) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *PushSignal) GetReceiverId() uint64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *PushSignal) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PushSignal) GetPartner() *AccountInfo {
	if x, ok := m.GetData().(*PushSignal_Partner); ok {
		return x.Partner
	}
	return nil
}

func (m *PushSignal) GetMsgId() string {
	if x, ok := m.GetData().(*PushSignal_MsgId); ok {
		return x.MsgId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PushSignal) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PushSignal_Partner)(nil),
		(*PushSignal_MsgId)(nil),
	}
}

type AccountInfo struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f209535e190f2bed, []int{4}
}
func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return m.Size()
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AccountInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.SignalTypeEnum", SignalTypeEnum_name, SignalTypeEnum_value)
	proto.RegisterType((*PushRequest)(nil), "proto.PushRequest")
	proto.RegisterType((*PushResp)(nil), "proto.PushResp")
	proto.RegisterType((*PushDialogue)(nil), "proto.PushDialogue")
	proto.RegisterType((*PushSignal)(nil), "proto.PushSignal")
	proto.RegisterType((*AccountInfo)(nil), "proto.AccountInfo")
}

func init() { proto.RegisterFile("broker.proto", fileDescriptor_f209535e190f2bed) }

var fileDescriptor_f209535e190f2bed = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x36, 0x4e, 0xd2, 0x4c, 0x9a, 0xc6, 0x9d, 0xd2, 0xca, 0x0a, 0x55, 0x14, 0x85, 0x4b,
	0x04, 0x52, 0x54, 0x05, 0x15, 0x55, 0x88, 0x4b, 0x93, 0x56, 0x34, 0x88, 0xa0, 0xca, 0xe1, 0x07,
	0x5c, 0x7b, 0x71, 0xad, 0x26, 0xbb, 0xc6, 0xbb, 0x46, 0x70, 0xe5, 0x2b, 0xf8, 0x24, 0x8e, 0x7c,
	0x02, 0x0a, 0xe2, 0xc8, 0x3f, 0x20, 0xaf, 0xd7, 0x8e, 0x93, 0x46, 0x70, 0x8a, 0xe7, 0xcd, 0x7b,
	0x33, 0x6f, 0x32, 0xb3, 0xb0, 0x77, 0x1b, 0xf1, 0x7b, 0x1a, 0x0d, 0xc2, 0x88, 0x4b, 0x8e, 0x15,
	0xf5, 0xd3, 0x6e, 0xcc, 0xb9, 0x1f, 0xb8, 0x29, 0xd6, 0x7b, 0x06, 0x8d, 0x9b, 0x58, 0xdc, 0xd9,
	0xf4, 0x63, 0x4c, 0x85, 0xc4, 0x13, 0xa8, 0x3b, 0xae, 0xcb, 0x63, 0x26, 0x27, 0x9e, 0x45, 0xba,
	0xa4, 0x6f, 0xd8, 0x2b, 0xa0, 0x77, 0x01, 0xbb, 0x29, 0x59, 0x84, 0xf8, 0x04, 0x0c, 0x97, 0x7b,
	0x54, 0x91, 0xf6, 0x87, 0xad, 0xb4, 0xdc, 0x60, 0xcc, 0x3d, 0x7a, 0xc5, 0xe2, 0x85, 0xad, 0x92,
	0x68, 0x42, 0x79, 0x21, 0x7c, 0x6b, 0xa7, 0x4b, 0xfa, 0x75, 0x3b, 0xf9, 0xec, 0x7d, 0x25, 0xb0,
	0x97, 0xd4, 0xb8, 0x0c, 0x9c, 0x39, 0xf7, 0x63, 0x8a, 0x6d, 0xd8, 0x15, 0x94, 0x79, 0x34, 0xca,
	0x1b, 0xe6, 0x71, 0xe2, 0x46, 0x50, 0x21, 0x02, 0xce, 0x26, 0x9e, 0x2a, 0x62, 0xd8, 0x2b, 0x00,
	0x3b, 0x00, 0x11, 0x75, 0x69, 0xf0, 0x49, 0x69, 0xcb, 0x2a, 0x5d, 0x40, 0xd0, 0x82, 0x9a, 0xcb,
	0x99, 0xa4, 0x4c, 0x5a, 0x86, 0x32, 0x90, 0x85, 0xbd, 0x3f, 0x04, 0x20, 0x31, 0x31, 0x0b, 0x7c,
	0xe6, 0xcc, 0xf1, 0x0c, 0x40, 0xa8, 0xaf, 0xf7, 0x5f, 0xc2, 0x6c, 0xa0, 0x23, 0x3d, 0xd0, 0x2c,
	0x4f, 0xa8, 0xb1, 0x0a, 0xc4, 0x35, 0xe7, 0x3b, 0x1b, 0xce, 0xff, 0xe7, 0x6d, 0x6d, 0x32, 0x63,
	0x73, 0xb2, 0x01, 0xd4, 0x42, 0x27, 0x92, 0x8c, 0x46, 0x56, 0xa5, 0x4b, 0xfa, 0x8d, 0x21, 0x6a,
	0x37, 0x17, 0x7a, 0x15, 0xec, 0x03, 0xbf, 0x2e, 0xd9, 0x19, 0x09, 0x8f, 0xa1, 0xb2, 0x10, 0xfe,
	0xc4, 0xb3, 0xaa, 0xc9, 0x9c, 0xd7, 0x25, 0x3b, 0x0d, 0x47, 0x55, 0x30, 0x3c, 0x47, 0x3a, 0xbd,
	0xd7, 0xd0, 0x28, 0x28, 0xff, 0xbd, 0xe4, 0x64, 0x2c, 0x16, 0xb8, 0xf7, 0xef, 0x9c, 0x05, 0xd5,
	0x8b, 0xcb, 0xe3, 0xa7, 0x63, 0xd8, 0x5f, 0xff, 0x43, 0xb0, 0x05, 0x8d, 0x9b, 0xd4, 0xc5, 0xd5,
	0xe7, 0x40, 0x9a, 0x25, 0x3c, 0x80, 0xe6, 0x38, 0xa2, 0x8e, 0xa4, 0xb3, 0x74, 0x1c, 0x93, 0x60,
	0x13, 0xea, 0x97, 0x74, 0x4e, 0x25, 0x9d, 0x0a, 0xdf, 0xdc, 0x19, 0xfe, 0x2e, 0x43, 0x75, 0xa4,
	0xee, 0x12, 0xdf, 0x64, 0x64, 0x6d, 0x0f, 0x1f, 0x67, 0x77, 0x54, 0x44, 0xf5, 0x71, 0xb6, 0x4f,
	0xb6, 0x27, 0x45, 0xc8, 0x99, 0xa0, 0x38, 0x84, 0xca, 0xd4, 0x91, 0xee, 0x1d, 0x1e, 0x6a, 0x9a,
	0x8a, 0x32, 0xed, 0xa3, 0x75, 0x50, 0x6b, 0xce, 0xa1, 0x36, 0xa3, 0xcc, 0x9b, 0x0a, 0x1f, 0xf3,
	0x85, 0xa7, 0x71, 0xa6, 0x3b, 0xde, 0x84, 0xb5, 0xf2, 0x0c, 0xaa, 0x6f, 0xb9, 0xcf, 0x63, 0x89,
	0x59, 0xe5, 0x34, 0xcc, 0x74, 0x47, 0x1b, 0xa8, 0x96, 0xbd, 0x82, 0x56, 0x72, 0x78, 0x53, 0xe1,
	0xe7, 0x0f, 0x20, 0xdb, 0x6d, 0xe1, 0x19, 0xb6, 0x0f, 0x0b, 0x58, 0x46, 0x3c, 0x25, 0x78, 0x0e,
	0x4d, 0xad, 0xd6, 0x97, 0xbb, 0x4d, 0x7b, 0x50, 0xc0, 0x52, 0xda, 0x29, 0xc1, 0x97, 0x80, 0x76,
	0x7a, 0x7d, 0xc5, 0xd6, 0xdb, 0xda, 0xb4, 0x5b, 0x6b, 0x35, 0x45, 0x88, 0x2f, 0xc0, 0x5c, 0x69,
	0x75, 0xe3, 0x87, 0x4d, 0x1e, 0xe8, 0x46, 0xe6, 0xf7, 0x65, 0x87, 0xfc, 0x58, 0x76, 0xc8, 0xcf,
	0x65, 0x87, 0x7c, 0xfb, 0xd5, 0x29, 0xdd, 0x56, 0x15, 0xe3, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x04, 0xd2, 0xae, 0x5c, 0x97, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerClient is the client API for Broker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	SendMsg(ctx context.Context, in *SendMsgRequest, opts ...grpc.CallOption) (*SendMsgResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// 给客户端推送数据的双向流
	PushMsgDialogue(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (Broker_PushMsgDialogueClient, error)
	PushMsgSignal(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (Broker_PushMsgSignalClient, error)
	// 接收logic推送过来的数据
	ReceiveMsgDialogue(ctx context.Context, in *PushDialogue, opts ...grpc.CallOption) (*PushResp, error)
	ReceiveMsgSignal(ctx context.Context, in *PushSignal, opts ...grpc.CallOption) (*PushResp, error)
}

type brokerClient struct {
	cc *grpc.ClientConn
}

func NewBrokerClient(cc *grpc.ClientConn) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.Broker/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, "/proto.Broker/Match", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) SendMsg(ctx context.Context, in *SendMsgRequest, opts ...grpc.CallOption) (*SendMsgResponse, error) {
	out := new(SendMsgResponse)
	err := c.cc.Invoke(ctx, "/proto.Broker/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/proto.Broker/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) PushMsgDialogue(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (Broker_PushMsgDialogueClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Broker_serviceDesc.Streams[0], "/proto.Broker/PushMsgDialogue", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerPushMsgDialogueClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broker_PushMsgDialogueClient interface {
	Recv() (*PushDialogue, error)
	grpc.ClientStream
}

type brokerPushMsgDialogueClient struct {
	grpc.ClientStream
}

func (x *brokerPushMsgDialogueClient) Recv() (*PushDialogue, error) {
	m := new(PushDialogue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *brokerClient) PushMsgSignal(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (Broker_PushMsgSignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Broker_serviceDesc.Streams[1], "/proto.Broker/PushMsgSignal", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerPushMsgSignalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broker_PushMsgSignalClient interface {
	Recv() (*PushSignal, error)
	grpc.ClientStream
}

type brokerPushMsgSignalClient struct {
	grpc.ClientStream
}

func (x *brokerPushMsgSignalClient) Recv() (*PushSignal, error) {
	m := new(PushSignal)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *brokerClient) ReceiveMsgDialogue(ctx context.Context, in *PushDialogue, opts ...grpc.CallOption) (*PushResp, error) {
	out := new(PushResp)
	err := c.cc.Invoke(ctx, "/proto.Broker/ReceiveMsgDialogue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) ReceiveMsgSignal(ctx context.Context, in *PushSignal, opts ...grpc.CallOption) (*PushResp, error) {
	out := new(PushResp)
	err := c.cc.Invoke(ctx, "/proto.Broker/ReceiveMsgSignal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServer is the server API for Broker service.
type BrokerServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	Match(context.Context, *MatchRequest) (*MatchResponse, error)
	SendMsg(context.Context, *SendMsgRequest) (*SendMsgResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// 给客户端推送数据的双向流
	PushMsgDialogue(*PushRequest, Broker_PushMsgDialogueServer) error
	PushMsgSignal(*PushRequest, Broker_PushMsgSignalServer) error
	// 接收logic推送过来的数据
	ReceiveMsgDialogue(context.Context, *PushDialogue) (*PushResp, error)
	ReceiveMsgSignal(context.Context, *PushSignal) (*PushResp, error)
}

// UnimplementedBrokerServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerServer struct {
}

func (*UnimplementedBrokerServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedBrokerServer) Match(ctx context.Context, req *MatchRequest) (*MatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Match not implemented")
}
func (*UnimplementedBrokerServer) SendMsg(ctx context.Context, req *SendMsgRequest) (*SendMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (*UnimplementedBrokerServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedBrokerServer) PushMsgDialogue(req *PushRequest, srv Broker_PushMsgDialogueServer) error {
	return status.Errorf(codes.Unimplemented, "method PushMsgDialogue not implemented")
}
func (*UnimplementedBrokerServer) PushMsgSignal(req *PushRequest, srv Broker_PushMsgSignalServer) error {
	return status.Errorf(codes.Unimplemented, "method PushMsgSignal not implemented")
}
func (*UnimplementedBrokerServer) ReceiveMsgDialogue(ctx context.Context, req *PushDialogue) (*PushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMsgDialogue not implemented")
}
func (*UnimplementedBrokerServer) ReceiveMsgSignal(ctx context.Context, req *PushSignal) (*PushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMsgSignal not implemented")
}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

func _Broker_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/Match",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Match(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).SendMsg(ctx, req.(*SendMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_PushMsgDialogue_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PushRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).PushMsgDialogue(m, &brokerPushMsgDialogueServer{stream})
}

type Broker_PushMsgDialogueServer interface {
	Send(*PushDialogue) error
	grpc.ServerStream
}

type brokerPushMsgDialogueServer struct {
	grpc.ServerStream
}

func (x *brokerPushMsgDialogueServer) Send(m *PushDialogue) error {
	return x.ServerStream.SendMsg(m)
}

func _Broker_PushMsgSignal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PushRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).PushMsgSignal(m, &brokerPushMsgSignalServer{stream})
}

type Broker_PushMsgSignalServer interface {
	Send(*PushSignal) error
	grpc.ServerStream
}

type brokerPushMsgSignalServer struct {
	grpc.ServerStream
}

func (x *brokerPushMsgSignalServer) Send(m *PushSignal) error {
	return x.ServerStream.SendMsg(m)
}

func _Broker_ReceiveMsgDialogue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDialogue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ReceiveMsgDialogue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/ReceiveMsgDialogue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ReceiveMsgDialogue(ctx, req.(*PushDialogue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_ReceiveMsgSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).ReceiveMsgSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Broker/ReceiveMsgSignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).ReceiveMsgSignal(ctx, req.(*PushSignal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Broker_CreateAccount_Handler,
		},
		{
			MethodName: "Match",
			Handler:    _Broker_Match_Handler,
		},
		{
			MethodName: "SendMsg",
			Handler:    _Broker_SendMsg_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Broker_Logout_Handler,
		},
		{
			MethodName: "ReceiveMsgDialogue",
			Handler:    _Broker_ReceiveMsgDialogue_Handler,
		},
		{
			MethodName: "ReceiveMsgSignal",
			Handler:    _Broker_ReceiveMsgSignal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushMsgDialogue",
			Handler:       _Broker_PushMsgDialogue_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushMsgSignal",
			Handler:       _Broker_PushMsgSignal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "broker.proto",
}

func (m *PushRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.AccountId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.AccountId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PushResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintBroker(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PushDialogue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushDialogue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushDialogue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Content) > 0 {
		i -= len(m.Content)
		copy(dAtA[i:], m.Content)
		i = encodeVarintBroker(dAtA, i, uint64(len(m.Content)))
		i--
		dAtA[i] = 0x22
	}
	if m.ReceiverId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.ReceiverId))
		i--
		dAtA[i] = 0x18
	}
	if m.SessionId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.SessionId))
		i--
		dAtA[i] = 0x10
	}
	if m.SenderId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.SenderId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PushSignal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushSignal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushSignal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Data != nil {
		{
			size := m.Data.Size()
			i -= size
			if _, err := m.Data.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.SessionId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.SessionId))
		i--
		dAtA[i] = 0x20
	}
	if m.ReceiverId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.ReceiverId))
		i--
		dAtA[i] = 0x18
	}
	if m.SenderId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.SenderId))
		i--
		dAtA[i] = 0x10
	}
	if m.SignalType != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.SignalType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PushSignal_Partner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushSignal_Partner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Partner != nil {
		{
			size, err := m.Partner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBroker(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *PushSignal_MsgId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushSignal_MsgId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.MsgId)
	copy(dAtA[i:], m.MsgId)
	i = encodeVarintBroker(dAtA, i, uint64(len(m.MsgId)))
	i--
	dAtA[i] = 0x32
	return len(dAtA) - i, nil
}
func (m *AccountInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.NickName) > 0 {
		i -= len(m.NickName)
		copy(dAtA[i:], m.NickName)
		i = encodeVarintBroker(dAtA, i, uint64(len(m.NickName)))
		i--
		dAtA[i] = 0x12
	}
	if m.AccountId != 0 {
		i = encodeVarintBroker(dAtA, i, uint64(m.AccountId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBroker(dAtA []byte, offset int, v uint64) int {
	offset -= sovBroker(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PushRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccountId != 0 {
		n += 1 + sovBroker(uint64(m.AccountId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PushResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovBroker(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovBroker(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PushDialogue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SenderId != 0 {
		n += 1 + sovBroker(uint64(m.SenderId))
	}
	if m.SessionId != 0 {
		n += 1 + sovBroker(uint64(m.SessionId))
	}
	if m.ReceiverId != 0 {
		n += 1 + sovBroker(uint64(m.ReceiverId))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovBroker(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PushSignal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SignalType != 0 {
		n += 1 + sovBroker(uint64(m.SignalType))
	}
	if m.SenderId != 0 {
		n += 1 + sovBroker(uint64(m.SenderId))
	}
	if m.ReceiverId != 0 {
		n += 1 + sovBroker(uint64(m.ReceiverId))
	}
	if m.SessionId != 0 {
		n += 1 + sovBroker(uint64(m.SessionId))
	}
	if m.Data != nil {
		n += m.Data.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PushSignal_Partner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Partner != nil {
		l = m.Partner.Size()
		n += 1 + l + sovBroker(uint64(l))
	}
	return n
}
func (m *PushSignal_MsgId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgId)
	n += 1 + l + sovBroker(uint64(l))
	return n
}
func (m *AccountInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccountId != 0 {
		n += 1 + sovBroker(uint64(m.AccountId))
	}
	l = len(m.NickName)
	if l > 0 {
		n += 1 + l + sovBroker(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBroker(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBroker(x uint64) (n int) {
	return sovBroker(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PushRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBroker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountId", wireType)
			}
			m.AccountId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBroker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PushResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBroker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= CodeEnum(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBroker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBroker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBroker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PushDialogue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBroker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushDialogue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushDialogue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderId", wireType)
			}
			m.SenderId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			m.SessionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverId", wireType)
			}
			m.ReceiverId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBroker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBroker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBroker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PushSignal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBroker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushSignal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushSignal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignalType", wireType)
			}
			m.SignalType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignalType |= SignalTypeEnum(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderId", wireType)
			}
			m.SenderId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverId", wireType)
			}
			m.ReceiverId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			m.SessionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Partner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBroker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBroker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AccountInfo{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Data = &PushSignal_Partner{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBroker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBroker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = &PushSignal_MsgId{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBroker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBroker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountId", wireType)
			}
			m.AccountId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NickName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBroker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBroker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NickName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBroker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBroker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBroker(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBroker
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBroker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBroker
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBroker
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBroker
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBroker        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBroker          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBroker = fmt.Errorf("proto: unexpected end of group")
)
