// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CodeEnum int32

const (
	CodeEnum_C000 CodeEnum = 0
	CodeEnum_C001 CodeEnum = 1
	CodeEnum_C002 CodeEnum = 2
	CodeEnum_C003 CodeEnum = 3
	CodeEnum_C004 CodeEnum = 4
)

var CodeEnum_name = map[int32]string{
	0: "C000",
	1: "C001",
	2: "C002",
	3: "C003",
	4: "C004",
}

var CodeEnum_value = map[string]int32{
	"C000": 0,
	"C001": 1,
	"C002": 2,
	"C003": 3,
	"C004": 4,
}

func (x CodeEnum) String() string {
	return proto.EnumName(CodeEnum_name, int32(x))
}

func (CodeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{0}
}

type StatusEnum int32

const (
	StatusEnum_Deleted StatusEnum = 0
	StatusEnum_Normal  StatusEnum = 1
)

var StatusEnum_name = map[int32]string{
	0: "Deleted",
	1: "Normal",
}

var StatusEnum_value = map[string]int32{
	"Deleted": 0,
	"Normal":  1,
}

func (x StatusEnum) String() string {
	return proto.EnumName(StatusEnum_name, int32(x))
}

func (StatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{1}
}

type MsgTypeEnum int32

const (
	MsgTypeEnum_Dialogue MsgTypeEnum = 0
	MsgTypeEnum_Signal   MsgTypeEnum = 1
)

var MsgTypeEnum_name = map[int32]string{
	0: "Dialogue",
	1: "Signal",
}

var MsgTypeEnum_value = map[string]int32{
	"Dialogue": 0,
	"Signal":   1,
}

func (x MsgTypeEnum) String() string {
	return proto.EnumName(MsgTypeEnum_name, int32(x))
}

func (MsgTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{2}
}

type CreateAccountRequest struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Broker               string   `protobuf:"bytes,2,opt,name=broker,proto3" json:"broker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateAccountRequest) GetBroker() string {
	if m != nil {
		return m.Broker
	}
	return ""
}

type CreateAccountResponse struct {
	Code                 CodeEnum `protobuf:"varint,1,opt,name=code,proto3,enum=proto.CodeEnum" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	AccountId            uint64   `protobuf:"varint,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{1}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetCode() CodeEnum {
	if m != nil {
		return m.Code
	}
	return CodeEnum_C000
}

func (m *CreateAccountResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateAccountResponse) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type MatchRequest struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchRequest) Reset()         { *m = MatchRequest{} }
func (m *MatchRequest) String() string { return proto.CompactTextString(m) }
func (*MatchRequest) ProtoMessage()    {}
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{2}
}

func (m *MatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchRequest.Unmarshal(m, b)
}
func (m *MatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchRequest.Marshal(b, m, deterministic)
}
func (m *MatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchRequest.Merge(m, src)
}
func (m *MatchRequest) XXX_Size() int {
	return xxx_messageInfo_MatchRequest.Size(m)
}
func (m *MatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MatchRequest proto.InternalMessageInfo

func (m *MatchRequest) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type MatchResponse struct {
	Code                 CodeEnum `protobuf:"varint,1,opt,name=code,proto3,enum=proto.CodeEnum" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	PartnerId            uint64   `protobuf:"varint,3,opt,name=partnerId,proto3" json:"partnerId,omitempty"`
	PartnerName          string   `protobuf:"bytes,4,opt,name=partnerName,proto3" json:"partnerName,omitempty"`
	SessionId            uint64   `protobuf:"varint,5,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchResponse) Reset()         { *m = MatchResponse{} }
func (m *MatchResponse) String() string { return proto.CompactTextString(m) }
func (*MatchResponse) ProtoMessage()    {}
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{3}
}

func (m *MatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchResponse.Unmarshal(m, b)
}
func (m *MatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchResponse.Marshal(b, m, deterministic)
}
func (m *MatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchResponse.Merge(m, src)
}
func (m *MatchResponse) XXX_Size() int {
	return xxx_messageInfo_MatchResponse.Size(m)
}
func (m *MatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MatchResponse proto.InternalMessageInfo

func (m *MatchResponse) GetCode() CodeEnum {
	if m != nil {
		return m.Code
	}
	return CodeEnum_C000
}

func (m *MatchResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *MatchResponse) GetPartnerId() uint64 {
	if m != nil {
		return m.PartnerId
	}
	return 0
}

func (m *MatchResponse) GetPartnerName() string {
	if m != nil {
		return m.PartnerName
	}
	return ""
}

func (m *MatchResponse) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type SendMsgRequest struct {
	SenderId             uint64      `protobuf:"varint,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	SessionId            uint64      `protobuf:"varint,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Msgtype              MsgTypeEnum `protobuf:"varint,4,opt,name=msgtype,proto3,enum=proto.MsgTypeEnum" json:"msgtype,omitempty"`
	Content              string      `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMsgRequest) Reset()         { *m = SendMsgRequest{} }
func (m *SendMsgRequest) String() string { return proto.CompactTextString(m) }
func (*SendMsgRequest) ProtoMessage()    {}
func (*SendMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{4}
}

func (m *SendMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgRequest.Unmarshal(m, b)
}
func (m *SendMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgRequest.Marshal(b, m, deterministic)
}
func (m *SendMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgRequest.Merge(m, src)
}
func (m *SendMsgRequest) XXX_Size() int {
	return xxx_messageInfo_SendMsgRequest.Size(m)
}
func (m *SendMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgRequest proto.InternalMessageInfo

func (m *SendMsgRequest) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *SendMsgRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SendMsgRequest) GetMsgtype() MsgTypeEnum {
	if m != nil {
		return m.Msgtype
	}
	return MsgTypeEnum_Dialogue
}

func (m *SendMsgRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendMsgResponse struct {
	Code                 CodeEnum `protobuf:"varint,1,opt,name=code,proto3,enum=proto.CodeEnum" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgResponse) Reset()         { *m = SendMsgResponse{} }
func (m *SendMsgResponse) String() string { return proto.CompactTextString(m) }
func (*SendMsgResponse) ProtoMessage()    {}
func (*SendMsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{5}
}

func (m *SendMsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgResponse.Unmarshal(m, b)
}
func (m *SendMsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgResponse.Marshal(b, m, deterministic)
}
func (m *SendMsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgResponse.Merge(m, src)
}
func (m *SendMsgResponse) XXX_Size() int {
	return xxx_messageInfo_SendMsgResponse.Size(m)
}
func (m *SendMsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgResponse proto.InternalMessageInfo

func (m *SendMsgResponse) GetCode() CodeEnum {
	if m != nil {
		return m.Code
	}
	return CodeEnum_C000
}

func (m *SendMsgResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LogoutRequest struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{6}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type LogoutResponse struct {
	Code                 CodeEnum `protobuf:"varint,1,opt,name=code,proto3,enum=proto.CodeEnum" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60207fea82c31ca8, []int{7}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetCode() CodeEnum {
	if m != nil {
		return m.Code
	}
	return CodeEnum_C000
}

func (m *LogoutResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.CodeEnum", CodeEnum_name, CodeEnum_value)
	proto.RegisterEnum("proto.StatusEnum", StatusEnum_name, StatusEnum_value)
	proto.RegisterEnum("proto.MsgTypeEnum", MsgTypeEnum_name, MsgTypeEnum_value)
	proto.RegisterType((*CreateAccountRequest)(nil), "proto.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "proto.CreateAccountResponse")
	proto.RegisterType((*MatchRequest)(nil), "proto.MatchRequest")
	proto.RegisterType((*MatchResponse)(nil), "proto.MatchResponse")
	proto.RegisterType((*SendMsgRequest)(nil), "proto.SendMsgRequest")
	proto.RegisterType((*SendMsgResponse)(nil), "proto.SendMsgResponse")
	proto.RegisterType((*LogoutRequest)(nil), "proto.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "proto.LogoutResponse")
}

func init() { proto.RegisterFile("logic.proto", fileDescriptor_60207fea82c31ca8) }

var fileDescriptor_60207fea82c31ca8 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x6e, 0x9b, 0x4e,
	0x10, 0x0e, 0x36, 0xfe, 0x37, 0xc4, 0x0e, 0xda, 0x5f, 0x1c, 0x21, 0x7e, 0x39, 0x58, 0x54, 0x55,
	0x23, 0x2b, 0x8d, 0x5c, 0xd2, 0x4a, 0x3d, 0xf4, 0x52, 0xd9, 0x55, 0x9b, 0x28, 0xce, 0x01, 0xf7,
	0x05, 0x08, 0x8c, 0x28, 0x0a, 0xec, 0x52, 0x76, 0x39, 0xe4, 0x35, 0xfa, 0x0c, 0x7d, 0xce, 0xaa,
	0x62, 0x59, 0x88, 0x41, 0x39, 0x54, 0xf2, 0x89, 0x99, 0x6f, 0xbf, 0xf9, 0xf8, 0x76, 0x66, 0x07,
	0x8c, 0x84, 0x45, 0x71, 0x70, 0x95, 0xe5, 0x4c, 0x30, 0x32, 0x90, 0x1f, 0xe7, 0x16, 0x4e, 0xd7,
	0x39, 0xfa, 0x02, 0x3f, 0x07, 0x01, 0x2b, 0xa8, 0xf0, 0xf0, 0x67, 0x81, 0x5c, 0x10, 0x1b, 0xc6,
	0x34, 0x0e, 0x1e, 0xa9, 0x9f, 0xa2, 0xa5, 0x2d, 0xb4, 0x8b, 0x89, 0xd7, 0xe4, 0xe4, 0x0c, 0x86,
	0x0f, 0x39, 0x7b, 0xc4, 0xdc, 0xea, 0xc9, 0x13, 0x95, 0x39, 0x09, 0xcc, 0x3b, 0x5a, 0x3c, 0x63,
	0x94, 0x23, 0x79, 0x05, 0x7a, 0xc0, 0xc2, 0x4a, 0x68, 0xe6, 0x9e, 0x54, 0x0e, 0xae, 0xd6, 0x2c,
	0xc4, 0x2f, 0xb4, 0x48, 0x3d, 0x79, 0x48, 0x4c, 0xe8, 0xa7, 0x3c, 0x52, 0x92, 0x65, 0x48, 0xce,
	0x61, 0xe2, 0x57, 0x4a, 0x37, 0xa1, 0xd5, 0x5f, 0x68, 0x17, 0xba, 0xf7, 0x0c, 0x38, 0x97, 0x70,
	0xbc, 0xf5, 0x45, 0xf0, 0xa3, 0x76, 0xdc, 0x62, 0x6b, 0x5d, 0xf6, 0x6f, 0x0d, 0xa6, 0x8a, 0x7e,
	0xb0, 0xa9, 0xcc, 0xcf, 0x05, 0xc5, 0xfc, 0xd9, 0x54, 0x03, 0x90, 0x05, 0x18, 0x2a, 0xb9, 0x2f,
	0x3b, 0xa7, 0xcb, 0xba, 0x7d, 0xa8, 0xac, 0xe7, 0xc8, 0x79, 0xcc, 0xe8, 0x4d, 0x68, 0x0d, 0xaa,
	0xfa, 0x06, 0x70, 0x7e, 0x69, 0x30, 0xdb, 0x21, 0x0d, 0xb7, 0x3c, 0xda, 0x9b, 0x04, 0x47, 0x1a,
	0xca, 0xff, 0xf5, 0x24, 0xbf, 0xc9, 0xdb, 0x62, 0xfd, 0x8e, 0x18, 0xb9, 0x84, 0x51, 0xca, 0x23,
	0xf1, 0x94, 0x55, 0x46, 0x66, 0x2e, 0x51, 0x97, 0xdc, 0xf2, 0xe8, 0xfb, 0x53, 0x56, 0xdd, 0xb3,
	0xa6, 0x10, 0x0b, 0x46, 0x01, 0xa3, 0x02, 0xa9, 0x90, 0xb6, 0x26, 0x5e, 0x9d, 0x3a, 0xdf, 0xe0,
	0xa4, 0xf1, 0x74, 0x50, 0xf3, 0x9c, 0xb7, 0x30, 0xbd, 0x63, 0x11, 0x2b, 0xc4, 0xbf, 0x0d, 0xed,
	0x2b, 0xcc, 0x6a, 0xfa, 0x41, 0xff, 0x5d, 0x7e, 0x82, 0x71, 0xcd, 0x21, 0x63, 0xd0, 0xd7, 0xab,
	0xd5, 0xca, 0x3c, 0x52, 0xd1, 0x3b, 0x53, 0x53, 0x91, 0x6b, 0xf6, 0x54, 0x74, 0x6d, 0xf6, 0x55,
	0xf4, 0xde, 0xd4, 0x97, 0xaf, 0x01, 0x76, 0xc2, 0x17, 0x05, 0x97, 0xf5, 0x06, 0x8c, 0x36, 0x98,
	0xa0, 0xc0, 0xd0, 0x3c, 0x22, 0x00, 0xc3, 0x7b, 0x96, 0xa7, 0x7e, 0x62, 0x6a, 0xcb, 0x37, 0x60,
	0xec, 0x35, 0x96, 0x1c, 0xc3, 0x78, 0x13, 0xfb, 0x09, 0x8b, 0x0a, 0xac, 0x88, 0xbb, 0x38, 0xa2,
	0x25, 0xd1, 0xfd, 0xa3, 0x81, 0x71, 0x57, 0xae, 0xe2, 0x06, 0xfd, 0x04, 0x73, 0x72, 0x0b, 0xd3,
	0xd6, 0xde, 0x90, 0xff, 0xeb, 0x7b, 0xbd, 0xb0, 0x99, 0xf6, 0xf9, 0xcb, 0x87, 0xaa, 0x41, 0x2e,
	0x0c, 0xe4, 0x33, 0x27, 0xff, 0xd5, 0xb3, 0xde, 0xdb, 0x11, 0xfb, 0xb4, 0x0d, 0xaa, 0x9a, 0x8f,
	0x30, 0x52, 0xf3, 0x25, 0x73, 0x45, 0x68, 0xbf, 0x41, 0xfb, 0xac, 0x0b, 0xab, 0xca, 0x0f, 0x30,
	0xac, 0x06, 0x44, 0x6a, 0xe5, 0xd6, 0x78, 0xed, 0x79, 0x07, 0xad, 0xca, 0x1e, 0x86, 0x12, 0xbd,
	0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x05, 0x09, 0x0c, 0xd3, 0x91, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogicDealerClient is the client API for LogicDealer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicDealerClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	SendMsg(ctx context.Context, in *SendMsgRequest, opts ...grpc.CallOption) (*SendMsgResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
}

type logicDealerClient struct {
	cc *grpc.ClientConn
}

func NewLogicDealerClient(cc *grpc.ClientConn) LogicDealerClient {
	return &logicDealerClient{cc}
}

func (c *logicDealerClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/proto.LogicDealer/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicDealerClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, "/proto.LogicDealer/Match", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicDealerClient) SendMsg(ctx context.Context, in *SendMsgRequest, opts ...grpc.CallOption) (*SendMsgResponse, error) {
	out := new(SendMsgResponse)
	err := c.cc.Invoke(ctx, "/proto.LogicDealer/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicDealerClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/proto.LogicDealer/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicDealerServer is the server API for LogicDealer service.
type LogicDealerServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	Match(context.Context, *MatchRequest) (*MatchResponse, error)
	SendMsg(context.Context, *SendMsgRequest) (*SendMsgResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
}

// UnimplementedLogicDealerServer can be embedded to have forward compatible implementations.
type UnimplementedLogicDealerServer struct {
}

func (*UnimplementedLogicDealerServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedLogicDealerServer) Match(ctx context.Context, req *MatchRequest) (*MatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Match not implemented")
}
func (*UnimplementedLogicDealerServer) SendMsg(ctx context.Context, req *SendMsgRequest) (*SendMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (*UnimplementedLogicDealerServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterLogicDealerServer(s *grpc.Server, srv LogicDealerServer) {
	s.RegisterService(&_LogicDealer_serviceDesc, srv)
}

func _LogicDealer_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicDealerServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogicDealer/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicDealerServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicDealer_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicDealerServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogicDealer/Match",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicDealerServer).Match(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicDealer_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicDealerServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogicDealer/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicDealerServer).SendMsg(ctx, req.(*SendMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicDealer_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicDealerServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LogicDealer/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicDealerServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicDealer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LogicDealer",
	HandlerType: (*LogicDealerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _LogicDealer_CreateAccount_Handler,
		},
		{
			MethodName: "Match",
			Handler:    _LogicDealer_Match_Handler,
		},
		{
			MethodName: "SendMsg",
			Handler:    _LogicDealer_SendMsg_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _LogicDealer_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic.proto",
}
