name: golang-ci

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:v1.54.0
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: golangci-lint
        run: golangci-lint run --modules-download-mode=mod

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
      - name: build broker
        run: go build -o chat-broker ./cmd/broker
      - name: build logic
        run: go build -o chat-logic ./cmd/logic
